CREATE TABLE [dbo].[users] (
    [id]                   VARCHAR (50)  CONSTRAINT [DF_users_id] DEFAULT ([dbo].[fn_GenerateUUIDv7]()) NOT NULL,
    [code]                 VARCHAR (50)  NULL,
    [username]             VARCHAR (50)  NOT NULL,
    [email]                VARCHAR (100) NOT NULL,
    [password_hash]        VARCHAR (255) NOT NULL,
    [first_name]           VARCHAR (100) NULL,
    [last_name]            VARCHAR (100) NULL,
    [phone_number]         VARCHAR (20)  NULL,
    [avatar_url]           VARCHAR (MAX) NULL,
    [avatar_media_file_id] INT           NULL,
    [gender]               VARCHAR (20)  NULL,
    [birth_date]           DATE          NULL,
    [address]              VARCHAR (MAX) NULL,
    [provider]             VARCHAR (50)  DEFAULT ('system') NULL,
    [role_id]              VARCHAR (50)  NULL,
    [is_active]            BIT           DEFAULT ((1)) NULL,
    [is_email_verified]    BIT           DEFAULT ((0)) NULL,
    [email_verified_at]    DATETIME2 (7) NULL,
    [last_login_at]        DATETIME2 (7) NULL,
    [created_at]           DATETIME2 (7) DEFAULT (getdate()) NULL,
    [updated_at]           DATETIME2 (7) DEFAULT (getdate()) NULL,
    [created_by]           INT           NULL,
    [updated_by]           INT           NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    UNIQUE NONCLUSTERED ([email] ASC),
    UNIQUE NONCLUSTERED ([username] ASC)
);

